#!/bin/bash
#Marshall’s fregrid combining script

conda deactivate
ml load netcdf/4.4.1.1
ml load gcc/10.1.0

Set -e

fregrid --input_mosaic C96_mosaic.nc --input_file 19790101.atmos_daily.nc --output_file dailyT2.nc --scalar_field temp --nthreads 6 --nlon 144 --nlat 90 --debug
